#!/bin/bash

DBUSER=''
DBPASSWORD=''

SHASUM=sha1sum # on RHEL
#SHASUM=shasum # on MACOS

SEDFLAG=-r # on RHEL
#SEDFLAG=-E # on MACOS

USERNAME=$1
USERMAIL=$2
USERPWD=$3

#RHEL VERSION
PWD=`echo -n $2$3 | $SHASUM | sed $SEDFLAG 's/[[:space:]]*-[[:space:]]*//'`

echo -n "INSERT INTO users VALUES ('name', 'email', 'password') VALUES ('$1', '$2', '$PWD');" | mysql -u $DBUSER "-p$DBPASSWORD" dossier
