#!/bin/bash

cd /home/apache/tools/scripts/

echo '/** ********************' > personaldossier.js
echo views/addBookmarkView.js  >> personaldossier.js
echo '******************** **/' >> personaldossier.js

cat views/addBookmarkView.js >> personaldossier.js

echo '' >> personaldossier.js
echo '/** ********************' >> personaldossier.js
echo controllers/addBookmarkController.js  >> personaldossier.js
echo '******************** **/' >> personaldossier.js

cat controllers/addBookmarkController.js >> personaldossier.js

cd -

